version: "3.9"
services:
    db:
        image: mysql
        restart: always
        volumes: 
            - ./mysql-startscripts:/docker-entrypoint-initdb.d
        environment: 
            - MYSQL_DATABASE=db_moodtracker
            - MYSQL_USER=springuser
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=1234
    moodtracker-server:
        container_name: moodtracker-server
        build: .
        depends_on: 
            - db
        ports:
            - 8080:8080
        links: 
            - db
        restart: always
